## ==================== APP & DEVICE CONFIG ====================
#platform=Android
#deviceName=emulator-5554
#automationName=UiAutomator2
#appPackage=com.watb.chefmate
#appActivity=com.watb.chefmate.ui.main.MainActivity
#
## ==================== APPIUM SERVER ====================
#appium.server.url=http://127.0.0.1:4723

# ==================== TIMEOUT ====================
implicit.wait=10
explicit.wait=15
page.load.timeout=20
#
#platform=Android
#deviceName=Samsung Galaxy A56
#automationName=UiAutomator2
##
#appPackage=com.watb.chefmate
#appActivity=com.watb.chefmate.ui.main.MainActivity
#
#udid=192.168.22.101:40217

#new.command.timeout=300
## ==================== TEST DATA ====================
#default.email=00000@gmail.com
#default.password=000000
#default.username=0000000000
#
## ==================== REPORTING ====================
#allure.results.directory=reports/allure
#google.sheet.enabled=false
#google.sheet.id=YOUR_GOOGLE_SHEET_ID
#google.sheet.name=ChefMate Automation Report

appium.server.url=http://127.0.0.1:4723

platform=Android
deviceName=Samsung Galaxy A56
emulatorName=emulator-5554
automationName=UiAutomator2

appPackage=com.watb.chefmate
appActivity=com.watb.chefmate.ui.main.MainActivity

#new.command.timeout=300

## ch\u1ECDn thi\u1EBFt b\u1ECB
#device=real
device=emulator
udid=emulator-5554
#udid=192.168.22.101:41631

#appium.server.url=http://127.0.0.1:4723
#
#platform=Android
#automationName=UiAutomator2
#
##device=emulator
###device=real
##
##emulator.udid=emulator-5554
##real.udid=192.168.22.101:41631
#
#appPackage=com.watb.chefmate
#appActivity=com.watb.chefmate.ui.main.MainActivity