name: ChefMate E2E

on:
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test-and-report:

    runs-on: self-hosted
    
    environment:
          name: github-pages
    steps:

      - uses: actions/checkout@v4

      - name: Verify Environment
        shell: cmd
        run: |
          java -version
          mvn -version
          adb version
          adb devices
      - name: Verify Emulator Ready
        shell: cmd
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed
          
      - name: Kill Existing Appium
        shell: cmd
        continue-on-error: true
        run: |
          taskkill /F /IM node.exe
          
      - name: Start Appium
        shell: powershell
        run: |
          Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/c appium --address 127.0.0.1 --port 4723" `
            -WindowStyle Hidden

      - name: Wait Appium
        shell: powershell
        run: |
          Start-Sleep -Seconds 20

      - name: Verify Appium
        shell: cmd
        run: |
          netstat -ano | findstr :4723

      - name: Run E2E Tests
        shell: cmd
        continue-on-error: true
        run: |
          mvn clean test -DsuiteXmlFile="suites/testng-e2e-integration.xml"  
          
      # Bước mới: Tự tạo Allure Report thành trang HTML tĩnh ngay trên máy của chị luôn (Không lo bị nghẽn mạng)
      - name: Generate Allure Report Locally
        if: always()
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure_results: target/allure-results
          allure_report: allure-report

      # Bước mới: Gom toàn bộ trang báo cáo đã tạo thành 1 file độc nhất để đẩy thẳng lên GitHub Pages
      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

      # Bước cuối: Kích hoạt Deploy thẳng lên link GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4
      
