name: ChefMate E2E

on:
  workflow_dispatch:

  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Verify Environment
        shell: cmd
        run: |
          java -version
          mvn -version
          adb version
          adb devices
      - name: Verify Emulator Ready
        shell: cmd
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed
      - name: Kill Existing Appium
        shell: cmd
        continue-on-error: true
        run: |
          taskkill /F /IM node.exe
      - name: Start Appium
        shell: powershell
        run: |
          Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/c appium --address 127.0.0.1 --port 4723" `
            -WindowStyle Hidden

      - name: Wait Appium
        shell: powershell
        run: |
          Start-Sleep -Seconds 20

      - name: Verify Appium
        shell: cmd
        run: |
          netstat -ano | findstr :4723

      - name: Run E2E Tests
        shell: cmd
        continue-on-error: true
        run: |
          mvn clean test -DsuiteXmlFile="suites/testng-e2e-integration.xml"

      - name: Cleanup Allure Temp Files
        if: always()
        shell: powershell
        run: |
          Get-ChildItem target/allure-results -Recurse `
            -Include *.tmp,*.log |
            Remove-Item -Force -ErrorAction SilentlyContinue
            
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          compression-level: 9

  allure:

    needs: test

    if: always()

    runs-on: ubuntu-latest

    steps:

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:

    needs: allure

    if: always()

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - uses: actions/deploy-pages@v4
