name: ChefMate E2E

on:
  workflow_dispatch:

  push:
    branches:
      - master
      
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:

  test:

    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Verify Environment
        run: |
          java -version
          mvn -version
          adb devices
        
      - name: Start Appium
        shell: cmd
        run: |
          taskkill /F /IM node.exe
          start /B appium

      - name: Wait Appium
        shell: powershell
        run: |
          Start-Sleep -Seconds 15

      - name: Run E2E Tests
        shell: cmd
        run: |
          mvn clean test -DsuiteXmlFile="suites/testng-e2e-integration.xml"

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          
  allure:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:

    needs: allure

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:

      - uses: actions/deploy-pages@v4
