name: ChefMate E2E

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check Maven
        run: mvn -version

      - name: Check Appium
        shell: cmd
        run: |
          "C:\Users\HOANG\AppData\Roaming\npm\appium.cmd" -v

      - name: Check Emulator
        run: |
          adb devices
