name: test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Check Java
        run: java -version

      - name: Check ADB
        run: adb devices

      - name: Check Emulator
        run: |
          adb wait-for-device
          adb shell getprop sys.boot_completed