name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Machine Info
        run: hostname

      - name: Java Version
        run: java -version

      - name: Maven Version
        run: mvn -version

      - name: Appium Version
        run: appium -v